// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1) {
  return window['go']['main']['App']['AddTodo'](arg1);
}

export function CountTodos() {
  return window['go']['main']['App']['CountTodos']();
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function GetAllTodos() {
  return window['go']['main']['App']['GetAllTodos']();
}

export function GetTodo(arg1) {
  return window['go']['main']['App']['GetTodo'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Sum(arg1, arg2) {
  return window['go']['main']['App']['Sum'](arg1, arg2);
}

export function UpdateTodo(arg1) {
  return window['go']['main']['App']['UpdateTodo'](arg1);
}
