// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTodo(arg1:main.Item):Promise<main.Item>;

export function CountTodos():Promise<number>;

export function DeleteTodo(arg1:number):Promise<void>;

export function GetAllTodos():Promise<Array<main.Item>>;

export function GetTodo(arg1:number):Promise<main.Item>;

export function Greet(arg1:string):Promise<string>;

export function Sum(arg1:number,arg2:number):Promise<number>;

export function UpdateTodo(arg1:main.Item):Promise<void>;
